name: Sync to Hugging Face
on:
  push:
    branches: [main]
  # Isse aap manually bhi trigger kar sakte hain GitHub Actions se
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Remote URL with Token
          git remote add hf https://vickey92:$HF_TOKEN@huggingface.co/spaces/vickey92/cv
          
          # Force push to overwrite HF space with GitHub code
          git push --force hf main
